version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true

http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin:
      - http://registry.home.arpa
    Access-Control-Allow-Methods:
      - HEAD
      - GET
      - OPTIONS
      - DELETE
    Access-Control-Allow-Headers:
      - Authorization
      - Accept
      - Accept-Version
      - Content-Type
      - Content-Length
      - Content-Range
      - Content-MD5
      - Content-Encoding
      - X-Requested-With
      - Origin
    Access-Control-Expose-Headers:
      - Docker-Content-Digest

metrics:
  prometheus:
    enabled: true
    path: /metrics
