global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node
    static_configs:
      - targets: ["${PI_IP_ADDRESS}:9100"]

  - job_name: pihole
    metrics_path: /metrics
    static_configs:
      - targets: ["pihole_exporter:9617"]

  - job_name: 'docker_engine'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9323']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: docker-engine

  - job_name: 'docker-registry'
    metrics_path: /metrics
    static_configs:
      - targets: ['registry:5000']