global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  # Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # Node (host) metrics
  - job_name: node
    static_configs:
      # Replace with your Pi's LAN IP if not 127.0.0.1
      - targets: ["192.168.4.117:9100"]

  # Pi-hole exporter
  - job_name: pihole
    metrics_path: /metrics
    static_configs:
      - targets: ["pihole_exporter:9617"]
