tunnel: 696c4908-29ff-41ae-bb3c-d7c9117187dd
credentials-file: /etc/cloudflared/696c4908-29ff-41ae-bb3c-d7c9117187dd.json

ingress:
  - hostname: grafana.devdevdeveau.net
    service: http://traefik:80
  - hostname: dns.devdevdeveau.net
    service: http://traefik:80
  - service: http_status:404